import { configApp } from '@adonisjs/eslint-config'

export default configApp({
  // Auto-generated by the Lucid schema generator on every `migration:run`;
  // formatting it would be reverted on the next run.
  name: 'ignore generated files',
  ignores: ['database/schema.ts'],
})
