/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import type { DownloadRenditionInfo } from '#transcodes/support/hls'
import type { SourceKind, TranscodeStatus } from '#transcodes/support/transcode_enums'

export class TranscodeSchema extends BaseModel {
  static $columns = ['archiveKey', 'callbackSecret', 'callbackUrl', 'createdAt', 'downloads', 'durationSeconds', 'error', 'id', 'originalFilename', 'outputPlaylist', 'sourceKind', 'sourceUrl', 'status', 'updatedAt'] as const
  $columns = TranscodeSchema.$columns
  @column()
  declare archiveKey: string | null
  @column({ serializeAs: null })
  declare callbackSecret: string | null
  @column()
  declare callbackUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare downloads: DownloadRenditionInfo[] | null
  @column()
  declare durationSeconds: number | null
  @column()
  declare error: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare originalFilename: string
  @column()
  declare outputPlaylist: string | null
  @column()
  declare sourceKind: SourceKind
  @column()
  declare sourceUrl: string | null
  @column()
  declare status: TranscodeStatus
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
